### PR TITLE
Making ASP.NET Core application always running on IIS

### PR DESCRIPTION
**Pull request by bamotav**
Making ASP.NET Core application always running on IIS.

### CODE REVIEW

**Comment by felixclase** [comment]
Cool! @odinserj, please review this change

**Comment by odinserj** [comment]
Wow, awesome @bamotav! :+1: :+1: :+1: :+1: :+1: Thanks a lot for contributing this!

**Comment by odinserj** [comment]
By the way, I see the images are blurry, and looks like you've optimized them for smaller size, that's really great. Just humbly wanted to let you know there's https://tinypng.com/ that optimizes PNGs without lowering the quality.

**Comment by bamotav** [comment]
Thanks @odinserj for the feedback, i'll fix it.

**Pull request merged**
