### PR TITLE
Small ASP.NET Core example code improvement

### PR DESCRIPTION
**Pull request by HenrikHoyer**

### CODE REVIEW

**Comment by odinserj** [comment]
May I ask you to try the code again? This is by intention, please see the `Configure` method where `IBackgroundJobClient` service is injected as a method parameter with the `backgroundJobs` name. It's better to use injected services in ASP.NET Core applications instead of static classes, e.g. `IBackgroundJobClient` instead of `BackgroundJob` and `IRecurringJobManager` instead of `RecurringJob`.

**Comment by HenrikHoyer** [comment]
You are correct. I did not notice the injected client in the Mvc example. 

Perhaps the client should be injected in the "endpoint routing" example below (including the ´"hello world" job )?

**Comment by odinserj** [comment]
May be, but it's not used in that example anyway.

**Comment by HenrikHoyer** [comment]
added `IBackgroundJobClient` injection to the second example

**Review by odinserj — APPROVED** [review]

**Comment by odinserj** [comment]
Thanks @HenrikHoyer!

**Pull request merged**
