### PR TITLE
Updated the version on the sample xml for csproj

### PR DESCRIPTION
**Pull request by jlimas**

### CODE REVIEW

**Comment by odinserj** [comment]
That's why there are badges on top of that XML, to not to bump versions there every time the new one is released. By the way, I've heard that we can specify version with the asterisk character like `Version="1.7.*"`, do you know if that's true?

image

**Comment by jlimas** [comment]
Yes that is correct

https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-versions

**Comment by odinserj** [comment]
That's really great, thank you for investigation and the fix!

**Comment by odinserj** [comment]
That's really awesome addition for new users – to have the latest version!

**Pull request merged**
